language: ruby
rvm: 2.0.0
script: _scripts/build.sh

branches:
  only:
  - development

deploy:
  provider: s3
  local-dir: Home
  access_key_id: ${AWS_S3_ACCESS_KEY}
  secret_access_key: ${AWS_S3_SECRET_KEY}
  bucket: "www.ourtransfi.org"
  acl: public_read

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
